// packages/plugin-loader/src/shared/components/file-picker.tsx
import { ChangeEvent, useEffect, useRef } from '@framework';
import { useLoaderCapability } from '../hooks';

/** Wrap the viewer root */
export function FilePicker() {
  const { provides: cap } = useLoaderCapability(); // capability
  const inputRef = useRef<HTMLInputElement>(null);

  /* ─── listen for “open file” requests ─── */
  useEffect(() => {
    if (!cap) return;
    const unsub = cap.onOpenFileRequest((req) => {
      if (req === 'open' && inputRef.current) inputRef.current.click();
    });
    return unsub;
  }, [cap]);

  /* ─── handle actual file selection ─── */
  const onChange = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = (e.currentTarget as HTMLInputElement).files?.[0];
    if (file && cap)
      cap.fileOpened(file);
      await cap.loadDocument({
        type: 'buffer',
        pdfFile: {
          id: Math.random().toString(36).substring(2, 15),
          name: file.name,
          content: await file.arrayBuffer(),
        },
      });
  };

  return (
    <>
      {/* Hidden picker */}
      <input
        ref={inputRef}
        type="file"
        accept="application/pdf"
        style={{ display: 'none' }}
        onChange={onChange}
      />
    </>
  );
}

// packages/plugin-loader/src/vue/components/file-picker.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useLoaderCapability } from '../hooks';

const { provides: loaderProvides } = useLoaderCapability();
const inputRef = ref<HTMLInputElement | null>(null);

let unsubscribe: (() => void) | null = null;

onMounted(() => {
  const cap = loaderProvides.value;
  if (!cap) return;

  // Listen for "open file" requests
  unsubscribe = cap.onOpenFileRequest((req) => {
    if (req === 'open' && inputRef.value) {
      inputRef.value.click();
    }
  });
});

onUnmounted(() => {
  if (unsubscribe) {
    unsubscribe();
  }
});

// Handle actual file selection
const onChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  const cap = loaderProvides.value;

  if (file && cap) {
    const arrayBuffer = await file.arrayBuffer();
    await cap.loadDocument({
      type: 'buffer',
      pdfFile: {
        id: Math.random().toString(36).substring(2, 15),
        name: file.name,
        content: arrayBuffer,
      },
    });
  }
};
</script>

<template>
  <!-- Hidden file picker -->
  <input
    ref="inputRef"
    type="file"
    accept="application/pdf"
    style="display: none"
    @change="onChange"
  />
</template>
