// packages/plugin-redaction/src/vue/components/redaction-layer.vue
<template>
  <PendingRedactions
    :page-index="pageIndex"
    :scale="scale"
    :rotation="rotation"
    :bbox-stroke="bboxStroke"
  >
    <template #selection-menu="slotProps">
      <slot name="selection-menu" v-bind="slotProps" />
    </template>
  </PendingRedactions>
  <MarqueeRedact :page-index="pageIndex" :scale="scale" />
  <SelectionRedact :page-index="pageIndex" :scale="scale" />
</template>

<script setup lang="ts">
import type { Rotation } from '@embedpdf/models';
import PendingRedactions from './pending-redactions.vue';
import MarqueeRedact from './marquee-redact.vue';
import SelectionRedact from './selection-redact.vue';

interface RedactionLayerProps {
  pageIndex: number;
  scale: number;
  rotation?: Rotation;
  bboxStroke?: string;
}

withDefaults(defineProps<RedactionLayerProps>(), {
  rotation: 0,
  bboxStroke: 'rgba(0,0,0,0.8)',
});
</script>

// packages/plugin-redaction/src/shared/components/redaction-layer.tsx
import { Fragment } from '@framework';
import { MarqueeRedact } from './marquee-redact';
import { SelectionRedact } from './selection-redact';
import { PendingRedactions } from './pending-redactions';
import { Rotation } from '@embedpdf/models';
import { SelectionMenuProps } from './types';

interface RedactionLayerProps {
  pageIndex: number;
  scale: number;
  rotation: Rotation;
  selectionMenu?: (props: SelectionMenuProps) => JSX.Element;
}

export const RedactionLayer = ({
  pageIndex,
  scale,
  rotation = Rotation.Degree0,
  selectionMenu,
}: RedactionLayerProps) => {
  return (
    <Fragment>
      <PendingRedactions
        pageIndex={pageIndex}
        scale={scale}
        rotation={rotation}
        selectionMenu={selectionMenu}
      />
      <MarqueeRedact pageIndex={pageIndex} scale={scale} />
      <SelectionRedact pageIndex={pageIndex} scale={scale} />
    </Fragment>
  );
};
