// packages/plugin-zoom/src/shared/components/pinch-wrapper.tsx
import { ReactNode, HTMLAttributes, CSSProperties } from '@framework';

import { usePinch } from '../hooks';

type PinchWrapperProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  children: ReactNode;
  style?: CSSProperties;
};

export function PinchWrapper({ children, style, ...props }: PinchWrapperProps) {
  const { elementRef } = usePinch();

  return (
    <div
      ref={elementRef}
      {...props}
      style={{
        ...style,
        display: 'block',
        width: 'fit-content',
        overflow: 'visible',
        boxSizing: 'border-box',
        margin: '0px auto',
      }}
    >
      {children}
    </div>
  );
}

// packages/plugin-zoom/src/svelte/components/PinchWrapper.svelte
<script lang="ts">
  import { usePinch } from '../hooks';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type PinchWrapperProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
    children: Snippet;
    class?: string;
  };

  let { children, class: propsClass, ...restProps }: PinchWrapperProps = $props();
  const pinch = usePinch();
</script>

<div
  bind:this={pinch.elementRef}
  {...restProps}
  style:display="block"
  style:width="fit-content"
  style:overflow="visible"
  style:box-sizing="border-box"
  style:margin="0px auto"
  class={propsClass}
>
  {children}
</div>
