// packages/plugin-selection/src/shared/components/selection-layer.tsx
import { useEffect, useState } from '@framework';
import { Rect } from '@embedpdf/models';
import { useSelectionCapability, useSelectionPlugin } from '../hooks';

type Props = {
  pageIndex: number;
  scale: number;
  background?: string;
};

export function SelectionLayer({ pageIndex, scale, background = 'rgba(33,150,243)' }: Props) {
  const { plugin: selPlugin } = useSelectionPlugin();
  const [rects, setRects] = useState<Rect[]>([]);
  const [boundingRect, setBoundingRect] = useState<Rect | null>(null);

  useEffect(() => {
    if (!selPlugin) return;

    return selPlugin.registerSelectionOnPage({
      pageIndex,
      onRectsChange: ({ rects, boundingRect }) => {
        setRects(rects);
        setBoundingRect(boundingRect);
      },
    });
  }, [selPlugin, pageIndex]);

  if (!boundingRect) return null;

  return (
    <div
      style={{
        position: 'absolute',
        left: boundingRect.origin.x * scale,
        top: boundingRect.origin.y * scale,
        width: boundingRect.size.width * scale,
        height: boundingRect.size.height * scale,
        mixBlendMode: 'multiply',
        isolation: 'isolate',
      }}
    >
      {rects.map((b, i) => (
        <div
          key={i}
          style={{
            position: 'absolute',
            left: (b.origin.x - boundingRect.origin.x) * scale,
            top: (b.origin.y - boundingRect.origin.y) * scale,
            width: b.size.width * scale,
            height: b.size.height * scale,
            background,
            pointerEvents: 'none',
          }}
        />
      ))}
    </div>
  );
}

// packages/plugin-selection/src/vue/components/selection-layer.vue
<template>
  <div
    v-if="boundingRect"
    :style="{
      position: 'absolute',
      left: `${boundingRect.origin.x * scale}px`,
      top: `${boundingRect.origin.y * scale}px`,
      width: `${boundingRect.size.width * scale}px`,
      height: `${boundingRect.size.height * scale}px`,
      mixBlendMode: 'multiply',
      isolation: 'isolate',
      pointerEvents: 'none',
    }"
  >
    <div
      v-for="(rect, i) in rects"
      :key="i"
      :style="{
        position: 'absolute',
        left: `${(rect.origin.x - boundingRect.origin.x) * scale}px`,
        top: `${(rect.origin.y - boundingRect.origin.y) * scale}px`,
        width: `${rect.size.width * scale}px`,
        height: `${rect.size.height * scale}px`,
        background: background,
      }"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import type { Rect } from '@embedpdf/models';
import { useSelectionPlugin } from '../hooks/use-selection';

interface Props {
  pageIndex: number;
  scale: number;
  background?: string;
}

const props = withDefaults(defineProps<Props>(), {
  background: 'rgba(33, 150, 243)',
});

const { plugin: sel } = useSelectionPlugin();
const rects = ref<Rect[]>([]);
const boundingRect = ref<Rect | null>(null);

let unregister: (() => void) | undefined;

onMounted(() => {
  if (!sel.value) return;

  unregister = sel.value.registerSelectionOnPage({
    pageIndex: props.pageIndex,
    onRectsChange: ({ rects: newRects, boundingRect: newBoundingRect }) => {
      rects.value = newRects;
      boundingRect.value = newBoundingRect;
    },
  });
});

onUnmounted(() => {
  unregister?.();
});
</script>
