// packages/plugin-viewport/src/vue/components/viewport.vue
<script setup lang="ts">
import { ref, watch, useAttrs } from 'vue';

import { useViewportCapability, useViewportRef } from '../hooks';

/* -------------------------------------------------- */
/* props & attrs                                      */
/* -------------------------------------------------- */
const attrs = useAttrs(); // forward class/id/… to <div>

/* -------------------------------------------------- */
/* plugin + reactive viewport gap                     */
/* -------------------------------------------------- */
const { provides: viewportProvides } = useViewportCapability();
const viewportGap = ref(0);

watch(
  viewportProvides,
  (vp) => {
    if (vp) viewportGap.value = vp.getViewportGap();
  },
  { immediate: true },
);

/* -------------------------------------------------- */
/* element ref that wires up scroll / resize logic    */
/* -------------------------------------------------- */
const viewportRef = useViewportRef();
</script>

<template>
  <div
    ref="viewportRef"
    v-bind="attrs"
    :style="{ padding: `${viewportGap}px`, width: '100%', height: '100%', overflow: 'auto' }"
  >
    <slot />
  </div>
</template>

// packages/plugin-viewport/src/shared/components/viewport.tsx
import { ReactNode, useEffect, useState, HTMLAttributes } from '@framework';

import { useViewportCapability } from '../hooks';
import { useViewportRef } from '../hooks/use-viewport-ref';

type ViewportProps = HTMLAttributes<HTMLDivElement> & {
  children: ReactNode;
};

export function Viewport({ children, ...props }: ViewportProps) {
  const [viewportGap, setViewportGap] = useState(0);
  const viewportRef = useViewportRef();
  const { provides: viewportProvides } = useViewportCapability();

  useEffect(() => {
    if (viewportProvides) {
      setViewportGap(viewportProvides.getViewportGap());
    }
  }, [viewportProvides]);

  const { style, ...restProps } = props;
  return (
    <div
      {...restProps}
      ref={viewportRef}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'auto',
        ...(typeof style === 'object' ? style : {}),
        padding: `${viewportGap}px`,
      }}
    >
      {children}
    </div>
  );
}
