// packages/plugin-viewport/src/svelte/components/Viewport.svelte
<script lang="ts">
  import { useViewportCapability, useViewportRef } from '../hooks';
  import type { HTMLAttributes } from 'svelte/elements';
  import type { Snippet } from 'svelte';

  type ViewportProps = HTMLAttributes<HTMLDivElement> & {
    children: Snippet;
    class?: string;
  };

  let { children, class: propsClass, ...restProps }: ViewportProps = $props();

  let viewportGap = $state(0);

  let viewportRef = useViewportRef();

  const viewportCapability = useViewportCapability();

  $effect(() => {
    if (viewportCapability.provides) {
      viewportGap = viewportCapability.provides.getViewportGap();
    }
  });
</script>

<div
  {...restProps}
  bind:this={viewportRef.containerRef}
  style:width="100%"
  style:height="100%"
  style:overflow="auto"
  style:padding={`${viewportGap}px`}
  class={propsClass}
>
  {@render children()}
</div>

// packages/plugin-viewport/src/shared/components/viewport.tsx
import { ReactNode, useEffect, useState, HTMLAttributes } from '@framework';

import { useViewportCapability } from '../hooks';
import { useViewportRef } from '../hooks/use-viewport-ref';

type ViewportProps = HTMLAttributes<HTMLDivElement> & {
  children: ReactNode;
};

export function Viewport({ children, ...props }: ViewportProps) {
  const [viewportGap, setViewportGap] = useState(0);
  const viewportRef = useViewportRef();
  const { provides: viewportProvides } = useViewportCapability();

  useEffect(() => {
    if (viewportProvides) {
      setViewportGap(viewportProvides.getViewportGap());
    }
  }, [viewportProvides]);

  const { style, ...restProps } = props;
  return (
    <div
      {...restProps}
      ref={viewportRef}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'auto',
        ...(typeof style === 'object' ? style : {}),
        padding: `${viewportGap}px`,
      }}
    >
      {children}
    </div>
  );
}
