// packages/plugin-capture/src/svelte/components/MarqueeCapture.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import { useCaptureCapability } from '../hooks/use-capture.svelte';

  interface MarqueeCaptureProps {
    /** Index of the page this layer lives on */
    pageIndex: number;
    /** Scale of the page */
    scale: number;
    /** Optional CSS class applied to the marquee rectangle */
    class?: string;
    /** Stroke / fill colours (defaults below) */
    stroke?: string;
    fill?: string;
  }

  let {
    pageIndex,
    scale,
    class: propsClass,
    stroke = 'rgba(33,150,243,0.8)',
    fill = 'rgba(33,150,243,0.15)',
  }: MarqueeCaptureProps = $props();

  const captureCapability = useCaptureCapability();
  let rect = $state<Rect | null>(null);

  $effect(() => {
    if (!captureCapability.provides) return;
    return captureCapability.provides.registerMarqueeOnPage({
      pageIndex,
      scale,
      callback: { onPreview: (val) => (rect = val) },
    });
  });
</script>

{#if rect}
  <div
    style:position="absolute"
    style:pointer-events="none"
    style:left={`${rect.origin.x * scale}px`}
    style:top={`${rect.origin.y * scale}px`}
    style:width={`${rect.size.width * scale}px`}
    style:height={`${rect.size.height * scale}px`}
    style:border={`1px solid ${stroke}`}
    style:background={fill}
    style:box-sizing="border-box"
    class={propsClass}
  ></div>
{/if}

// packages/plugin-capture/src/shared/components/marquee-capture.tsx
import { useEffect, useState } from '@framework';
import { Rect } from '@embedpdf/models';

import { useCaptureCapability } from '../hooks/use-capture';

interface MarqueeCaptureProps {
  /** Index of the page this layer lives on */
  pageIndex: number;
  /** Scale of the page */
  scale: number;
  /** Optional CSS class applied to the marquee rectangle */
  className?: string;
  /** Stroke / fill colours (defaults below) */
  stroke?: string;
  fill?: string;
}

export const MarqueeCapture = ({
  pageIndex,
  scale,
  className,
  stroke = 'rgba(33,150,243,0.8)',
  fill = 'rgba(33,150,243,0.15)',
}: MarqueeCaptureProps) => {
  const { provides: capturePlugin } = useCaptureCapability();
  const [rect, setRect] = useState<Rect | null>(null);

  useEffect(() => {
    if (!capturePlugin) return;
    return capturePlugin.registerMarqueeOnPage({
      pageIndex,
      scale,
      callback: {
        onPreview: setRect,
      },
    });
  }, [capturePlugin, pageIndex, scale]);

  if (!rect) return null;

  return (
    <div
      style={{
        position: 'absolute',
        pointerEvents: 'none',
        left: rect.origin.x * scale,
        top: rect.origin.y * scale,
        width: rect.size.width * scale,
        height: rect.size.height * scale,
        border: `1px solid ${stroke}`,
        background: fill,
        boxSizing: 'border-box',
      }}
      className={className}
    />
  );
};
