// packages/engines/src/vue/components/pdf-engine-provider.vue
<script setup lang="ts">
import { provide, toRefs } from 'vue';
import { pdfEngineKey } from '../context/pdf-engine-context';
import type { PdfEngine } from '@embedpdf/models';

interface Props {
  engine: PdfEngine | null;
  isLoading: boolean;
  error: Error | null;
}

const props = defineProps<Props>();

// Convert props to refs and provide them
const { engine, isLoading, error } = toRefs(props);

provide(pdfEngineKey, {
  engine,
  isLoading,
  error,
});
</script>

<template>
  <slot />
</template>

// packages/engines/src/svelte/components/PdfEngineProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { PdfEngine } from '@embedpdf/models';
  import { setPdfEngineContext } from '../context';

  interface Props {
    children: Snippet;
    engine: PdfEngine | null;
    isLoading: boolean;
    error: Error | null;
  }

  let { children, engine, isLoading, error }: Props = $props();

  // Update context reactively whenever props change
  $effect(() => {
    setPdfEngineContext({
      engine,
      isLoading,
      error,
    });
  });
</script>

{@render children()}
