// packages/plugin-annotation/src/vue/components/preview-renderer.vue
<template>
  <div :style="style">
    <Circle
      v-if="preview.type === PdfAnnotationSubtype.CIRCLE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Square
      v-else-if="preview.type === PdfAnnotationSubtype.SQUARE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Polygon
      v-else-if="preview.type === PdfAnnotationSubtype.POLYGON"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Polyline
      v-else-if="preview.type === PdfAnnotationSubtype.POLYLINE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Line
      v-else-if="preview.type === PdfAnnotationSubtype.LINE"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <Ink
      v-else-if="preview.type === PdfAnnotationSubtype.INK"
      :isSelected="false"
      :scale="scale"
      v-bind="preview.data"
    />
    <div
      v-else-if="preview.type === PdfAnnotationSubtype.FREETEXT"
      :style="{
        width: '100%',
        height: '100%',
        border: `1px dashed ${preview.data.fontColor || '#000000'}`,
        backgroundColor: 'transparent',
      }"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, CSSProperties } from 'vue';
import { AnyPreviewState } from '@embedpdf/plugin-annotation';
import { PdfAnnotationSubtype } from '@embedpdf/models';
import { Circle, Square, Polygon, Polyline, Line, Ink } from './annotations';

const props = defineProps<{
  preview: AnyPreviewState;
  scale: number;
}>();

const style = computed<CSSProperties>(() => ({
  position: 'absolute',
  left: `${props.preview.bounds.origin.x * props.scale}px`,
  top: `${props.preview.bounds.origin.y * props.scale}px`,
  width: `${props.preview.bounds.size.width * props.scale}px`,
  height: `${props.preview.bounds.size.height * props.scale}px`,
  pointerEvents: 'none',
  zIndex: 10,
}));
</script>

// packages/plugin-annotation/src/shared/components/preview-renderer.tsx
import { AnyPreviewState } from '@embedpdf/plugin-annotation';
import { Circle } from './annotations/circle';
import { Square } from './annotations/square';
import { Polygon } from './annotations/polygon';
import { PdfAnnotationSubtype } from '@embedpdf/models';
import { Polyline } from './annotations/polyline';
import { Line } from './annotations/line';
import { Ink } from './annotations/ink';

interface Props {
  preview: AnyPreviewState;
  scale: number;
}

export function PreviewRenderer({ preview, scale }: Props) {
  const { bounds } = preview;

  const style = {
    position: 'absolute' as const,
    left: bounds.origin.x * scale,
    top: bounds.origin.y * scale,
    width: bounds.size.width * scale,
    height: bounds.size.height * scale,
    pointerEvents: 'none' as const,
    zIndex: 10,
  };

  // Use type guards for proper type narrowing
  if (preview.type === PdfAnnotationSubtype.CIRCLE) {
    return (
      <div style={style}>
        <Circle isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.SQUARE) {
    return (
      <div style={style}>
        <Square isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.POLYGON) {
    return (
      <div style={style}>
        <Polygon isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.POLYLINE) {
    return (
      <div style={style}>
        <Polyline isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.LINE) {
    return (
      <div style={style}>
        <Line isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.INK) {
    return (
      <div style={style}>
        <Ink isSelected={false} scale={scale} {...preview.data} />
      </div>
    );
  }

  if (preview.type === PdfAnnotationSubtype.FREETEXT) {
    return (
      <div style={style}>
        {/* Render a simple dashed border preview */}
        <div
          style={{
            width: '100%',
            height: '100%',
            border: `1px dashed ${preview.data.fontColor || '#000000'}`,
            backgroundColor: 'transparent',
          }}
        />
      </div>
    );
  }

  return null;
}
