// packages/plugin-interaction-manager/src/svelte/components/GlobalPointerProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { useInteractionManagerCapability } from '../hooks';
  import { createPointerProvider } from '../../shared/utils';
  import type { HTMLAttributes } from 'svelte/elements';

  interface GlobalPointerProviderProps extends HTMLAttributes<HTMLDivElement> {
    children: Snippet;
    class?: string;
  }

  let { children, class: propsClass, ...restProps }: GlobalPointerProviderProps = $props();

  let ref = $state<HTMLDivElement | null>(null);
  const interactionManagerCapability = useInteractionManagerCapability();

  $effect(() => {
    if (!interactionManagerCapability.provides || !ref) return;

    return createPointerProvider(interactionManagerCapability.provides, { type: 'global' }, ref);
  });
</script>

<div bind:this={ref} style:width="100%" style:height="100%" class={propsClass} {...restProps}>
  {@render children()}
</div>

// packages/plugin-interaction-manager/src/shared/components/global-pointer-provider.tsx
import { ReactNode, useEffect, useRef, HTMLAttributes, CSSProperties } from '@framework';
import { createPointerProvider } from '../utils';

import { useInteractionManagerCapability } from '../hooks';

interface GlobalPointerProviderProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
  style?: CSSProperties;
}

export const GlobalPointerProvider = ({
  children,
  style,
  ...props
}: GlobalPointerProviderProps) => {
  const ref = useRef<HTMLDivElement>(null);
  const { provides: cap } = useInteractionManagerCapability();

  useEffect(() => {
    if (!cap || !ref.current) return;

    return createPointerProvider(cap, { type: 'global' }, ref.current);
  }, [cap]);

  return (
    <div
      ref={ref}
      style={{
        width: '100%',
        height: '100%',
        ...style,
      }}
      {...props}
    >
      {children}
    </div>
  );
};
