// packages/plugin-interaction-manager/src/vue/components/global-pointer-provider.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue';
import { createPointerProvider } from '../../shared/utils';
import { useInteractionManagerCapability } from '../hooks';

const divRef = ref<HTMLDivElement | null>(null);
const { provides: cap } = useInteractionManagerCapability();

// watchEffect automatically handles setup and teardown when capability or element is ready
watchEffect((onCleanup) => {
  if (cap.value && divRef.value) {
    const cleanup = createPointerProvider(cap.value, { type: 'global' }, divRef.value);
    onCleanup(cleanup);
  }
});
</script>

<template>
  <div
    ref="divRef"
    :style="{
      width: '100%',
      height: '100%',
    }"
  >
    <slot />
  </div>
</template>

// packages/plugin-interaction-manager/src/shared/components/global-pointer-provider.tsx
import { ReactNode, useEffect, useRef, HTMLAttributes, CSSProperties } from '@framework';
import { createPointerProvider } from '../utils';

import { useInteractionManagerCapability } from '../hooks';

interface GlobalPointerProviderProps extends HTMLAttributes<HTMLDivElement> {
  children: ReactNode;
  style?: CSSProperties;
}

export const GlobalPointerProvider = ({
  children,
  style,
  ...props
}: GlobalPointerProviderProps) => {
  const ref = useRef<HTMLDivElement>(null);
  const { provides: cap } = useInteractionManagerCapability();

  useEffect(() => {
    if (!cap || !ref.current) return;

    return createPointerProvider(cap, { type: 'global' }, ref.current);
  }, [cap]);

  return (
    <div
      ref={ref}
      style={{
        width: '100%',
        height: '100%',
        ...style,
      }}
      {...props}
    >
      {children}
    </div>
  );
};
