// packages/plugin-render/src/svelte/components/RenderLayer.svelte
<script lang="ts">
  import type { HTMLImgAttributes } from 'svelte/elements';
  import { ignore, type PdfDocumentObject, PdfErrorCode } from '@embedpdf/models';
  import { useRenderCapability, useRenderPlugin } from '../hooks';

  interface RenderLayerProps extends Omit<HTMLImgAttributes, 'style'> {
    pageIndex: number;
    scale?: number;
    dpr?: number;
    class?: string;
  }

  let { pageIndex, scale, dpr, class: propsClass, ...props }: RenderLayerProps = $props();

  const renderCapability = useRenderCapability();
  const renderPlugin = useRenderPlugin();

  const actualScale = $derived(scale ?? 1);

  let imageUrl = $state<string | null>(null);
  let urlRef: string | null = null;
  let refreshTick = $state(0);

  // Subscribe/unsubscribe whenever the plugin instance changes (not just on mount)
  $effect(() => {
    if (!renderPlugin.plugin) return; // nothing yet; try again when it appears
    return renderPlugin.plugin.onRefreshPages((pages) => {
      if (pages.includes(pageIndex)) {
        refreshTick++; // trigger a re-render
      }
    });
  });

  // Render whenever inputs change (pageIndex, scale, dpr, provides, refreshTick)
  $effect(() => {
    // Explicitly read refreshTick so the effect tracks it
    const _tick = refreshTick;

    const provides = renderCapability.provides;
    if (!provides) return;

    const task = provides.renderPage({
      pageIndex,
      options: { scaleFactor: actualScale, dpr: dpr || window.devicePixelRatio },
    });

    task.wait((blob) => {
      const url = URL.createObjectURL(blob);
      // revoke any previous URL before swapping to avoid leaks
      if (urlRef) {
        URL.revokeObjectURL(urlRef);
      }

      imageUrl = url;
      urlRef = url;
    }, ignore);

    return () => {
      if (urlRef) {
        URL.revokeObjectURL(urlRef);
        urlRef = null;
      } else {
        task.abort({
          code: PdfErrorCode.Cancelled,
          message: 'canceled render task',
        });
      }
    };
  });

  function handleImageLoad() {
    // Additional safety: once the image has loaded, revoke the last ref if still present
    if (urlRef) {
      URL.revokeObjectURL(urlRef);
      urlRef = null;
    }
  }
</script>

{#if imageUrl}
  <img
    src={imageUrl}
    onload={handleImageLoad}
    {...props}
    style="width: 100%; height: 100%;"
    class={propsClass}
    alt=""
  />
{/if}

// packages/plugin-render/src/vue/components/render-layer.vue
<script setup lang="ts">
import { ref, onBeforeUnmount, computed, watchEffect } from 'vue';
import { ignore, PdfErrorCode } from '@embedpdf/models';

import { useRenderCapability, useRenderPlugin } from '../hooks';

interface Props {
  pageIndex: number;
  /**
   * The scale factor for rendering the page.
   */
  scale?: number;
  /**
   * @deprecated Use `scale` instead. Will be removed in the next major release.
   */
  scaleFactor?: number;
  dpr?: number;
}

const props = defineProps<Props>();

// Handle deprecation: prefer scale over scaleFactor, but fall back to scaleFactor if scale is not provided
const actualScale = computed(() => props.scale ?? props.scaleFactor ?? 1);
const actualDpr = computed(() => props.dpr ?? window.devicePixelRatio);

const { provides: renderProvides } = useRenderCapability();
const { plugin: renderPlugin } = useRenderPlugin();

const imageUrl = ref<string | null>(null);
const refreshTick = ref(0);

let urlRef: string | null = null;
let hasLoaded = false;

// Listen for external page refresh events
watchEffect((onCleanup) => {
  if (!renderPlugin.value) return;

  const unsubscribe = renderPlugin.value.onRefreshPages((pages: number[]) => {
    if (pages.includes(props.pageIndex)) {
      refreshTick.value++;
    }
  });

  onCleanup(unsubscribe);
});

// Render page when dependencies change
watchEffect((onCleanup) => {
  // Capture reactive dependencies
  const pageIndex = props.pageIndex;
  const scale = actualScale.value;
  const dpr = actualDpr.value;
  const tick = refreshTick.value;
  const capability = renderProvides.value;

  if (!capability) return;

  // Revoke old URL before creating new one (if it's been loaded)
  if (urlRef && hasLoaded) {
    URL.revokeObjectURL(urlRef);
    urlRef = null;
    hasLoaded = false;
  }

  const task = capability.renderPage({
    pageIndex,
    options: {
      scaleFactor: scale,
      dpr,
    },
  });

  task.wait((blob) => {
    const objectUrl = URL.createObjectURL(blob);
    urlRef = objectUrl;
    imageUrl.value = objectUrl;
    hasLoaded = false;
  }, ignore);

  onCleanup(() => {
    if (urlRef) {
      // Only revoke if image has loaded
      if (hasLoaded) {
        URL.revokeObjectURL(urlRef);
        urlRef = null;
        hasLoaded = false;
      }
    } else {
      // Task still in progress, abort it
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
    }
  });
});

onBeforeUnmount(() => {
  if (urlRef) {
    URL.revokeObjectURL(urlRef);
    urlRef = null;
  }
});

function handleImageLoad() {
  hasLoaded = true;
}
</script>

<template>
  <img
    v-if="imageUrl"
    :src="imageUrl"
    :style="{ width: '100%', height: '100%' }"
    @load="handleImageLoad"
  />
</template>
