// packages/plugin-rotate/src/shared/components/rotate.tsx
import { ReactNode, HTMLAttributes, CSSProperties } from '@framework';
import { Size } from '@embedpdf/models';

import { useRotatePlugin } from '../hooks';

type RotateProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  children: ReactNode;
  pageSize: Size;
  style?: CSSProperties;
};

export function Rotate({ children, pageSize, style, ...props }: RotateProps) {
  const { plugin: rotate } = useRotatePlugin();
  const matrix =
    rotate?.getMatrixAsString({
      w: pageSize.width,
      h: pageSize.height,
    }) || 'matrix(1, 0, 0, 1, 0, 0)';

  return (
    <div
      {...props}
      style={{
        position: 'absolute',
        transformOrigin: '0 0',
        transform: matrix,
        ...style,
      }}
    >
      {children}
    </div>
  );
}

// packages/plugin-rotate/src/svelte/components/Rotate.svelte
<script lang="ts">
  import type { Size } from '@embedpdf/models';
  import type { Snippet } from 'svelte';
  import { useRotatePlugin } from '../hooks';

  interface RotateProps {
    pageSize: Size;
    children?: Snippet;
  }

  let { pageSize, children }: RotateProps = $props();

  const rotatePlugin = useRotatePlugin();

  const transformMatrix = $derived(
    rotatePlugin.plugin
      ? rotatePlugin.plugin.getMatrixAsString({
          w: pageSize.width,
          h: pageSize.height,
        })
      : 'matrix(1, 0, 0, 1, 0, 0)',
  );
</script>

<div style:position="absolute" style:transform-origin="0 0" style:transform={transformMatrix}>
  {@render children?.()}
</div>
